apiVersion: v1
kind: Service
metadata:
  name: product-microservice
  namespace: scalable-svc
  labels:                           # Added labels section
    app: product-microservice       # Label: app with value product-microservice
spec:
  selector:
    app: product-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9996
  type: LoadBalancer